version: '3.3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    networks:
      - sonarnet
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sonar
      MYSQL_USER: sonar
      MYSQL_PASSWORD: sonar

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"
    networks:
      - sonarnet
    volumes:
      - nexus_data:/nexus-data
      - nexus_backups:/nexus-backups

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - sonarnet
    volumes:
      - ./prometheus:/etc/prometheus

networks:
  sonarnet:

volumes:
  nexus_data:
  nexus_backups:
