version: '3.3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    networks:
      - sonarnet
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sonar
      MYSQL_USER: sonar
      MYSQL_PASSWORD: sonar

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"
    networks:
      - sonarnet
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Dnexus.security.needFirstUserSetup=false
    volumes:
      - nexus_data:/nexus-data
      - nexus_backups:/nexus-backups
    command: ["sh", "-c", "echo 'admin.password=$(openssl rand -base64 30)' > /nexus-data/admin.password && cat /nexus-data/admin.password && exec /opt/sonatype/nexus/bin/nexus run"]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - sonarnet

networks:
  sonarnet:

volumes:
  nexus_data:
  nexus_backups:
